#############################################################################
# Makefile for building: MediaLibrary
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  MediaLibrary.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile MediaLibrary.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MediaLibrary1.0.0
DISTDIR = /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/.tmp/MediaLibrary1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/items/AbstractItem.cpp \
		src/items/album.cpp \
		src/items/Books.cpp \
		src/items/Comic.cpp \
		src/items/movie.cpp \
		src/items/Videogames.cpp \
		src/jsonXml/JsonReader.cpp \
		src/jsonXml/JsonVisitor.cpp \
		src/jsonXml/JsonWriter.cpp \
		src/jsonXml/XmlParser.cpp \
		src/jsonXml/XmlVisitor.cpp \
		src/jsonXml/XmlWriter.cpp \
		src/library/ItemController.cpp \
		src/library/Library.cpp \
		src/library/SaveEditsVisitor.cpp \
		src/view/ItemDetailVisitor.cpp \
		src/view/ItemDetailWidget.cpp \
		src/view/LengthEdit.cpp \
		src/view/LibraryListModel.cpp \
		src/view/LibraryMainWindow.cpp \
		src/view/LibraryModelFilter.cpp \
		src/view/NewTitleDialog.cpp \
		src/view/SideMenu.cpp \
		src/view/StyleSetup.cpp \
		src/view/ThumbnailDelegate.cpp \
		src/view/NewItemForms/AlbumForm.cpp \
		src/view/NewItemForms/BookForm.cpp \
		src/view/NewItemForms/ComicForm.cpp \
		src/view/NewItemForms/MovieForm.cpp \
		src/view/NewItemForms/NewItemForm.cpp \
		src/view/NewItemForms/VideogameForm.cpp qrc_resources.cpp \
		moc_ItemController.cpp \
		moc_Library.cpp \
		moc_ItemDetailWidget.cpp \
		moc_LengthEdit.cpp \
		moc_LibraryListModel.cpp \
		moc_LibraryMainWindow.cpp \
		moc_LibraryModelFilter.cpp \
		moc_NewTitleDialog.cpp \
		moc_SideMenu.cpp \
		moc_ThumbnailDelegate.cpp \
		moc_AlbumForm.cpp \
		moc_BookForm.cpp \
		moc_ComicForm.cpp \
		moc_MovieForm.cpp \
		moc_NewItemForm.cpp \
		moc_VideogameForm.cpp
OBJECTS       = main.o \
		AbstractItem.o \
		album.o \
		Books.o \
		Comic.o \
		movie.o \
		Videogames.o \
		JsonReader.o \
		JsonVisitor.o \
		JsonWriter.o \
		XmlParser.o \
		XmlVisitor.o \
		XmlWriter.o \
		ItemController.o \
		Library.o \
		SaveEditsVisitor.o \
		ItemDetailVisitor.o \
		ItemDetailWidget.o \
		LengthEdit.o \
		LibraryListModel.o \
		LibraryMainWindow.o \
		LibraryModelFilter.o \
		NewTitleDialog.o \
		SideMenu.o \
		StyleSetup.o \
		ThumbnailDelegate.o \
		AlbumForm.o \
		BookForm.o \
		ComicForm.o \
		MovieForm.o \
		NewItemForm.o \
		VideogameForm.o \
		qrc_resources.o \
		moc_ItemController.o \
		moc_Library.o \
		moc_ItemDetailWidget.o \
		moc_LengthEdit.o \
		moc_LibraryListModel.o \
		moc_LibraryMainWindow.o \
		moc_LibraryModelFilter.o \
		moc_NewTitleDialog.o \
		moc_SideMenu.o \
		moc_ThumbnailDelegate.o \
		moc_AlbumForm.o \
		moc_BookForm.o \
		moc_ComicForm.o \
		moc_MovieForm.o \
		moc_NewItemForm.o \
		moc_VideogameForm.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MediaLibrary.pro src/items/AbstractItem.h \
		src/items/album.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/ItemVisitor.h \
		src/items/movie.h \
		src/items/Videogames.h \
		src/jsonXml/JsonReader.h \
		src/jsonXml/JsonVisitor.h \
		src/jsonXml/JsonWriter.h \
		src/jsonXml/XmlParser.h \
		src/jsonXml/XmlVisitor.h \
		src/jsonXml/XmlWriter.h \
		src/library/ItemController.h \
		src/library/Library.h \
		src/library/SaveEditsVisitor.h \
		src/view/ItemDetailVisitor.h \
		src/view/ItemDetailWidget.h \
		src/view/LengthEdit.h \
		src/view/LibraryListModel.h \
		src/view/LibraryMainWindow.h \
		src/view/LibraryModelFilter.h \
		src/view/NewTitleDialog.h \
		src/view/SideMenu.h \
		src/view/StyleSetup.h \
		src/view/ThumbnailDelegate.h \
		src/view/NewItemForms/AlbumForm.h \
		src/view/NewItemForms/BookForm.h \
		src/view/NewItemForms/ComicForm.h \
		src/view/NewItemForms/MovieForm.h \
		src/view/NewItemForms/NewItemForm.h \
		src/view/NewItemForms/VideogameForm.h src/main.cpp \
		src/items/AbstractItem.cpp \
		src/items/album.cpp \
		src/items/Books.cpp \
		src/items/Comic.cpp \
		src/items/movie.cpp \
		src/items/Videogames.cpp \
		src/jsonXml/JsonReader.cpp \
		src/jsonXml/JsonVisitor.cpp \
		src/jsonXml/JsonWriter.cpp \
		src/jsonXml/XmlParser.cpp \
		src/jsonXml/XmlVisitor.cpp \
		src/jsonXml/XmlWriter.cpp \
		src/library/ItemController.cpp \
		src/library/Library.cpp \
		src/library/SaveEditsVisitor.cpp \
		src/view/ItemDetailVisitor.cpp \
		src/view/ItemDetailWidget.cpp \
		src/view/LengthEdit.cpp \
		src/view/LibraryListModel.cpp \
		src/view/LibraryMainWindow.cpp \
		src/view/LibraryModelFilter.cpp \
		src/view/NewTitleDialog.cpp \
		src/view/SideMenu.cpp \
		src/view/StyleSetup.cpp \
		src/view/ThumbnailDelegate.cpp \
		src/view/NewItemForms/AlbumForm.cpp \
		src/view/NewItemForms/BookForm.cpp \
		src/view/NewItemForms/ComicForm.cpp \
		src/view/NewItemForms/MovieForm.cpp \
		src/view/NewItemForms/NewItemForm.cpp \
		src/view/NewItemForms/VideogameForm.cpp
QMAKE_TARGET  = MediaLibrary
DESTDIR       = 
TARGET        = MediaLibrary


first: all
####### Build rules

MediaLibrary:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MediaLibrary.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MediaLibrary.pro \
		assets/resources.qrc
	$(QMAKE) -o Makefile MediaLibrary.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
MediaLibrary.pro:
assets/resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile MediaLibrary.pro

qmake_all: FORCE


all: Makefile MediaLibrary

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents assets/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/items/AbstractItem.h src/items/album.h src/items/Books.h src/items/Comic.h src/items/ItemVisitor.h src/items/movie.h src/items/Videogames.h src/jsonXml/JsonReader.h src/jsonXml/JsonVisitor.h src/jsonXml/JsonWriter.h src/jsonXml/XmlParser.h src/jsonXml/XmlVisitor.h src/jsonXml/XmlWriter.h src/library/ItemController.h src/library/Library.h src/library/SaveEditsVisitor.h src/view/ItemDetailVisitor.h src/view/ItemDetailWidget.h src/view/LengthEdit.h src/view/LibraryListModel.h src/view/LibraryMainWindow.h src/view/LibraryModelFilter.h src/view/NewTitleDialog.h src/view/SideMenu.h src/view/StyleSetup.h src/view/ThumbnailDelegate.h src/view/NewItemForms/AlbumForm.h src/view/NewItemForms/BookForm.h src/view/NewItemForms/ComicForm.h src/view/NewItemForms/MovieForm.h src/view/NewItemForms/NewItemForm.h src/view/NewItemForms/VideogameForm.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/items/AbstractItem.cpp src/items/album.cpp src/items/Books.cpp src/items/Comic.cpp src/items/movie.cpp src/items/Videogames.cpp src/jsonXml/JsonReader.cpp src/jsonXml/JsonVisitor.cpp src/jsonXml/JsonWriter.cpp src/jsonXml/XmlParser.cpp src/jsonXml/XmlVisitor.cpp src/jsonXml/XmlWriter.cpp src/library/ItemController.cpp src/library/Library.cpp src/library/SaveEditsVisitor.cpp src/view/ItemDetailVisitor.cpp src/view/ItemDetailWidget.cpp src/view/LengthEdit.cpp src/view/LibraryListModel.cpp src/view/LibraryMainWindow.cpp src/view/LibraryModelFilter.cpp src/view/NewTitleDialog.cpp src/view/SideMenu.cpp src/view/StyleSetup.cpp src/view/ThumbnailDelegate.cpp src/view/NewItemForms/AlbumForm.cpp src/view/NewItemForms/BookForm.cpp src/view/NewItemForms/ComicForm.cpp src/view/NewItemForms/MovieForm.cpp src/view/NewItemForms/NewItemForm.cpp src/view/NewItemForms/VideogameForm.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: assets/resources.qrc \
		/usr/lib/qt5/bin/rcc \
		assets/icons/album.png \
		assets/icons/comic.png \
		assets/icons/all.png \
		assets/icons/book.png \
		assets/icons/videogame.png \
		assets/icons/edit.png \
		assets/icons/movie.png
	/usr/lib/qt5/bin/rcc -name resources assets/resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_ItemController.cpp moc_Library.cpp moc_ItemDetailWidget.cpp moc_LengthEdit.cpp moc_LibraryListModel.cpp moc_LibraryMainWindow.cpp moc_LibraryModelFilter.cpp moc_NewTitleDialog.cpp moc_SideMenu.cpp moc_ThumbnailDelegate.cpp moc_AlbumForm.cpp moc_BookForm.cpp moc_ComicForm.cpp moc_MovieForm.cpp moc_NewItemForm.cpp moc_VideogameForm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ItemController.cpp moc_Library.cpp moc_ItemDetailWidget.cpp moc_LengthEdit.cpp moc_LibraryListModel.cpp moc_LibraryMainWindow.cpp moc_LibraryModelFilter.cpp moc_NewTitleDialog.cpp moc_SideMenu.cpp moc_ThumbnailDelegate.cpp moc_AlbumForm.cpp moc_BookForm.cpp moc_ComicForm.cpp moc_MovieForm.cpp moc_NewItemForm.cpp moc_VideogameForm.cpp
moc_ItemController.cpp: src/library/ItemController.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/library/ItemController.h -o moc_ItemController.cpp

moc_Library.cpp: src/library/Library.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/library/Library.h -o moc_Library.cpp

moc_ItemDetailWidget.cpp: src/view/ItemDetailWidget.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/ItemDetailWidget.h -o moc_ItemDetailWidget.cpp

moc_LengthEdit.cpp: src/view/LengthEdit.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/LengthEdit.h -o moc_LengthEdit.cpp

moc_LibraryListModel.cpp: src/view/LibraryListModel.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/LibraryListModel.h -o moc_LibraryListModel.cpp

moc_LibraryMainWindow.cpp: src/view/LibraryMainWindow.h \
		src/view/ItemDetailWidget.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/view/LibraryListModel.h \
		src/view/LibraryModelFilter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/LibraryMainWindow.h -o moc_LibraryMainWindow.cpp

moc_LibraryModelFilter.cpp: src/view/LibraryModelFilter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/LibraryModelFilter.h -o moc_LibraryModelFilter.cpp

moc_NewTitleDialog.cpp: src/view/NewTitleDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/NewTitleDialog.h -o moc_NewTitleDialog.cpp

moc_SideMenu.cpp: src/view/SideMenu.h \
		src/view/LibraryModelFilter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/SideMenu.h -o moc_SideMenu.cpp

moc_ThumbnailDelegate.cpp: src/view/ThumbnailDelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/ThumbnailDelegate.h -o moc_ThumbnailDelegate.cpp

moc_AlbumForm.cpp: src/view/NewItemForms/AlbumForm.h \
		src/view/NewItemForms/NewItemForm.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/NewItemForms/AlbumForm.h -o moc_AlbumForm.cpp

moc_BookForm.cpp: src/view/NewItemForms/BookForm.h \
		src/view/NewItemForms/NewItemForm.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/NewItemForms/BookForm.h -o moc_BookForm.cpp

moc_ComicForm.cpp: src/view/NewItemForms/ComicForm.h \
		src/view/NewItemForms/NewItemForm.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/NewItemForms/ComicForm.h -o moc_ComicForm.cpp

moc_MovieForm.cpp: src/view/NewItemForms/MovieForm.h \
		src/view/NewItemForms/NewItemForm.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/NewItemForms/MovieForm.h -o moc_MovieForm.cpp

moc_NewItemForm.cpp: src/view/NewItemForms/NewItemForm.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/NewItemForms/NewItemForm.h -o moc_NewItemForm.cpp

moc_VideogameForm.cpp: src/view/NewItemForms/VideogameForm.h \
		src/view/NewItemForms/NewItemForm.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/mnt/server1/1/2023/tceron/Documents/MediaLibrary25/MediaLibrary -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/view/NewItemForms/VideogameForm.h -o moc_VideogameForm.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/library/Library.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/view/LibraryListModel.h \
		src/view/LibraryMainWindow.h \
		src/view/ItemDetailWidget.h \
		src/view/LibraryModelFilter.h \
		src/view/StyleSetup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

AbstractItem.o: src/items/AbstractItem.cpp src/items/AbstractItem.h \
		src/items/ItemVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractItem.o src/items/AbstractItem.cpp

album.o: src/items/album.cpp src/items/album.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o album.o src/items/album.cpp

Books.o: src/items/Books.cpp src/items/Books.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Books.o src/items/Books.cpp

Comic.o: src/items/Comic.cpp src/items/Comic.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Comic.o src/items/Comic.cpp

movie.o: src/items/movie.cpp src/items/movie.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movie.o src/items/movie.cpp

Videogames.o: src/items/Videogames.cpp src/items/Videogames.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Videogames.o src/items/Videogames.cpp

JsonReader.o: src/jsonXml/JsonReader.cpp src/jsonXml/JsonReader.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/items/movie.h \
		src/items/Videogames.h \
		src/items/Comic.h \
		src/items/Books.h \
		src/items/album.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonReader.o src/jsonXml/JsonReader.cpp

JsonVisitor.o: src/jsonXml/JsonVisitor.cpp src/jsonXml/JsonVisitor.h \
		src/items/album.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonVisitor.o src/jsonXml/JsonVisitor.cpp

JsonWriter.o: src/jsonXml/JsonWriter.cpp src/jsonXml/JsonWriter.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/jsonXml/JsonVisitor.h \
		src/items/album.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonWriter.o src/jsonXml/JsonWriter.cpp

XmlParser.o: src/jsonXml/XmlParser.cpp src/jsonXml/XmlParser.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/items/album.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlParser.o src/jsonXml/XmlParser.cpp

XmlVisitor.o: src/jsonXml/XmlVisitor.cpp src/jsonXml/XmlVisitor.h \
		src/items/ItemVisitor.h \
		src/items/album.h \
		src/items/AbstractItem.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlVisitor.o src/jsonXml/XmlVisitor.cpp

XmlWriter.o: src/jsonXml/XmlWriter.cpp src/jsonXml/XmlWriter.h \
		src/library/Library.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/jsonXml/XmlVisitor.h \
		src/items/album.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlWriter.o src/jsonXml/XmlWriter.cpp

ItemController.o: src/library/ItemController.cpp src/library/ItemController.h \
		src/library/Library.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/items/album.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ItemController.o src/library/ItemController.cpp

Library.o: src/library/Library.cpp src/library/Library.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/jsonXml/JsonReader.h \
		src/items/movie.h \
		src/items/Videogames.h \
		src/items/Comic.h \
		src/items/Books.h \
		src/items/album.h \
		src/jsonXml/JsonWriter.h \
		src/jsonXml/JsonVisitor.h \
		src/jsonXml/XmlParser.h \
		src/jsonXml/XmlWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Library.o src/library/Library.cpp

SaveEditsVisitor.o: src/library/SaveEditsVisitor.cpp src/library/SaveEditsVisitor.h \
		src/items/ItemVisitor.h \
		src/items/album.h \
		src/items/AbstractItem.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h \
		src/library/Library.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SaveEditsVisitor.o src/library/SaveEditsVisitor.cpp

ItemDetailVisitor.o: src/view/ItemDetailVisitor.cpp src/view/ItemDetailVisitor.h \
		src/items/ItemVisitor.h \
		src/view/ItemDetailWidget.h \
		src/items/AbstractItem.h \
		src/items/album.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h \
		src/library/SaveEditsVisitor.h \
		src/view/LengthEdit.h \
		src/library/Library.h \
		src/view/NewTitleDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ItemDetailVisitor.o src/view/ItemDetailVisitor.cpp

ItemDetailWidget.o: src/view/ItemDetailWidget.cpp src/view/ItemDetailWidget.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/view/ItemDetailVisitor.h \
		src/items/album.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ItemDetailWidget.o src/view/ItemDetailWidget.cpp

LengthEdit.o: src/view/LengthEdit.cpp src/view/LengthEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LengthEdit.o src/view/LengthEdit.cpp

LibraryListModel.o: src/view/LibraryListModel.cpp src/view/LibraryListModel.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/items/album.h \
		src/items/Books.h \
		src/items/Comic.h \
		src/items/movie.h \
		src/items/Videogames.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LibraryListModel.o src/view/LibraryListModel.cpp

LibraryMainWindow.o: src/view/LibraryMainWindow.cpp src/view/LibraryMainWindow.h \
		src/view/ItemDetailWidget.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h \
		src/view/LibraryListModel.h \
		src/view/LibraryModelFilter.h \
		src/library/Library.h \
		src/view/ThumbnailDelegate.h \
		src/view/SideMenu.h \
		src/view/NewItemForms/AlbumForm.h \
		src/view/NewItemForms/NewItemForm.h \
		src/view/NewItemForms/BookForm.h \
		src/view/NewItemForms/ComicForm.h \
		src/view/NewItemForms/MovieForm.h \
		src/view/NewItemForms/VideogameForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LibraryMainWindow.o src/view/LibraryMainWindow.cpp

LibraryModelFilter.o: src/view/LibraryModelFilter.cpp src/view/LibraryModelFilter.h \
		src/view/LibraryListModel.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LibraryModelFilter.o src/view/LibraryModelFilter.cpp

NewTitleDialog.o: src/view/NewTitleDialog.cpp src/view/NewTitleDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewTitleDialog.o src/view/NewTitleDialog.cpp

SideMenu.o: src/view/SideMenu.cpp src/view/SideMenu.h \
		src/view/LibraryModelFilter.h \
		src/view/LibraryListModel.h \
		src/items/AbstractItem.h \
		src/items/ItemVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SideMenu.o src/view/SideMenu.cpp

StyleSetup.o: src/view/StyleSetup.cpp src/view/StyleSetup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StyleSetup.o src/view/StyleSetup.cpp

ThumbnailDelegate.o: src/view/ThumbnailDelegate.cpp src/view/ThumbnailDelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThumbnailDelegate.o src/view/ThumbnailDelegate.cpp

AlbumForm.o: src/view/NewItemForms/AlbumForm.cpp src/view/NewItemForms/AlbumForm.h \
		src/view/NewItemForms/NewItemForm.h \
		src/library/ItemController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AlbumForm.o src/view/NewItemForms/AlbumForm.cpp

BookForm.o: src/view/NewItemForms/BookForm.cpp src/view/NewItemForms/BookForm.h \
		src/view/NewItemForms/NewItemForm.h \
		src/library/ItemController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BookForm.o src/view/NewItemForms/BookForm.cpp

ComicForm.o: src/view/NewItemForms/ComicForm.cpp src/view/NewItemForms/ComicForm.h \
		src/view/NewItemForms/NewItemForm.h \
		src/library/ItemController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ComicForm.o src/view/NewItemForms/ComicForm.cpp

MovieForm.o: src/view/NewItemForms/MovieForm.cpp src/view/NewItemForms/MovieForm.h \
		src/view/NewItemForms/NewItemForm.h \
		src/library/ItemController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieForm.o src/view/NewItemForms/MovieForm.cpp

NewItemForm.o: src/view/NewItemForms/NewItemForm.cpp src/view/NewItemForms/NewItemForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewItemForm.o src/view/NewItemForms/NewItemForm.cpp

VideogameForm.o: src/view/NewItemForms/VideogameForm.cpp src/view/NewItemForms/VideogameForm.h \
		src/view/NewItemForms/NewItemForm.h \
		src/library/ItemController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VideogameForm.o src/view/NewItemForms/VideogameForm.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_ItemController.o: moc_ItemController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ItemController.o moc_ItemController.cpp

moc_Library.o: moc_Library.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Library.o moc_Library.cpp

moc_ItemDetailWidget.o: moc_ItemDetailWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ItemDetailWidget.o moc_ItemDetailWidget.cpp

moc_LengthEdit.o: moc_LengthEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LengthEdit.o moc_LengthEdit.cpp

moc_LibraryListModel.o: moc_LibraryListModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LibraryListModel.o moc_LibraryListModel.cpp

moc_LibraryMainWindow.o: moc_LibraryMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LibraryMainWindow.o moc_LibraryMainWindow.cpp

moc_LibraryModelFilter.o: moc_LibraryModelFilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LibraryModelFilter.o moc_LibraryModelFilter.cpp

moc_NewTitleDialog.o: moc_NewTitleDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewTitleDialog.o moc_NewTitleDialog.cpp

moc_SideMenu.o: moc_SideMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SideMenu.o moc_SideMenu.cpp

moc_ThumbnailDelegate.o: moc_ThumbnailDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ThumbnailDelegate.o moc_ThumbnailDelegate.cpp

moc_AlbumForm.o: moc_AlbumForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AlbumForm.o moc_AlbumForm.cpp

moc_BookForm.o: moc_BookForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BookForm.o moc_BookForm.cpp

moc_ComicForm.o: moc_ComicForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ComicForm.o moc_ComicForm.cpp

moc_MovieForm.o: moc_MovieForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MovieForm.o moc_MovieForm.cpp

moc_NewItemForm.o: moc_NewItemForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewItemForm.o moc_NewItemForm.cpp

moc_VideogameForm.o: moc_VideogameForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VideogameForm.o moc_VideogameForm.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

